# Generated by Django 3.0.1 on 2019-12-18 15:40

from django.db import migrations

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'museum.json'
def load_data(apps, schema_editor):
    Stop = apps.get_model('stops', 'Stop')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    if tags.get('tourism'):
                         category = tags.get('tourism')
                    elif tags.get('amenity'):
                         category = tags.get('amenity')
                    elif tags.get('building'):
                         category = tags.get('building')
                    address = tags.get('addr:full')
                    city = 'Istanbul'
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Stop(name=name, category=category, location = location, address=address,city = city).save()
            except KeyError:
                pass     

class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
