# Generated by Django 3.0.1 on 2019-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_auto_20191218_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='desc',
            field=models.CharField(default="No description available yet.", max_length=350),
            preserve_default=False,
        ),
    ]
