# Generated by Django 3.0.1 on 2019-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0004_auto_20191222_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='photograph',
            field=models.ImageField(blank=True, upload_to='stop_image'),
        ),
    ]
